#!/usr/bin/env bash
# brew_update 1.1.0
# Does a thorough update of all installed Homebrew packages

printf "==> bash $BASH_VERSION\n==> "
brew --version
brew update
brew upgrade
brew list --cask | xargs brew upgrade
brew cleanup
