#!/usr/bin/env bash
# brew_update 1.3.1
# Does a thorough update of all installed Homebrew packages

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

printf "==> ${Gre}brew update ; brew upgrade ; brew cleanup${Rst}\n"
brew update
brew upgrade
brew list --cask | xargs brew upgrade
brew cleanup
