#!/usr/bin/env bash
# dl 1.2.0
# A simple yt-dlp, the famous video downloader, stub driver

# Install yt-dl:
#   curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
#     -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp
#
#   Upgrade yt-dl:
#     yt-dlp --update-to nightly
#     yt-dlp --version
#

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVerFile=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null)
    if [[ "$LatestVerFile" =~ ^\#\! ]]; then
        LatestVer=$(echo "$LatestVerFile" | sed -n '2p' | awk '{print $NF}')
        if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
            printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
            printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
        fi
    fi
}
check_version

if [[ "$#" -ne 2 ]]; then
    printf "Usage: $0 FILENAME \"URL\"\n"
    exit
fi
Filename="$1"
Url="$2"
Ext=`echo ${Filename##*.} | awk '{print tolower($0)}'` # Extension in lowercase

# Add MP4 extension if missing
if [[ "$Ext" != "mp4" ]]; then
    Filename="${Filename}.mp4"
fi

# Abort if file already exists
if [[ -e "$Filename" ]]; then
    echo File already exists
    exit 1
fi

# Download as MP4
yt-dlp -o "$Filename" --recode mp4 "$Url"

exit 0
