#!/bin/bash
# dl 1.0.5
# A simple yt-dlp, the famous video downloader, stub driver

# Install yt-dl:
#   curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
#     -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp
#
#   Upgrade yt-dl:
#     yt-dlp --update-to nightly
#     yt-dlp --version
#   

if [[ "$#" -ne 2 ]]; then
    printf "Usage: $0 FILENAME \"URL\"\n"
    exit
fi
Filename="$1"
Url="$2"
Ext=`echo ${Filename##*.} | awk '{print tolower($0)}'` # Extension in lowercase

# Add MP4 extension if missing
if [[ "$Ext" != "mp4" ]]; then
    Filename="${Filename}.mp4"
fi

# Abort if file already exists
if [[ -e "$Filename" ]]; then
    echo File already exists
    exit 1
fi

# Download as MP4
yt-dlp -o "$Filename" --recode mp4 "$Url"

exit 0
