#!/usr/bin/env bash
# git_statall 1.1.1
# Run status on all git repos

set -euo pipefail  # Fail on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
    fi
}

check_version

for r in $(ls -1) ; do
    if [[ -d "$r/.git" ]]; then
        (
            printf "%-50s" "$r"
            cd $r
            Branch="$(git branch --show-current)"
            if [[ "$(git status | grep 'working tree clean')" ]]; then
                printf "👍 $Branch\n"
            else
                printf "❌ $Branch\n"
            fi
        )
    fi
done
