#!/usr/bin/env bash
# git_remotev 1.1.1
# List remote sources of all git repos

set -euo pipefail
for r in `ls -d */` ; do
    r=${r%?}
    if [[ -d "$r/.git" ]]; then
        (
            cd "$r"
            git remote -v | awk '{print $2}'
        )
    fi
done | sort | uniq
exit 0
