#!/usr/bin/env bash
# git_cloneall 1.3.0
# Clone all repos for given Github Org or Username

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVerFile=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null)
    if [[ "$LatestVerFile" =~ ^\#\! ]]; then
        LatestVer=$(echo "$LatestVerFile" | sed -n '2p' | awk '{print $NF}')
        if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
            printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
            printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
        fi
    fi
}
check_version

usage() {
    echo "Usage: $(basename $0) <org/username>"
    exit 1
}

# Check binary exists
check_binary() {
    printf "==> Checking for ${Yel}$1${Rst} ... "
    if [[ -z "$(which $1 2>/dev/null)" ]]; then
        printf "${Red}missing${Rst}!\n"
    else
        printf "${Gre}found${Rst}\n"
    fi
}

# Check if an argument is provided
if [[ -z "${1:-}" ]]; then
    usage
fi
ORG_USERNAME=$1

# Confirm required binaries are available
for B in git gh ; do
    check_binary $B
done

repos=$(gh repo list "$ORG_USERNAME" --json name --jq '.[].name')

# Loop through each repository
for repo in $repos; do
    # Check if the directory already exists
    if [[ -d "$repo" ]]; then
        printf "==> ${Yel}Warning: Directory '$repo' already exists. Skipping...${Rst}"
    else
        printf "==> ${Yel}Cloning '$repo'...${Rst}"
        git clone "https://github.com/$ORG_USERNAME/$repo.git"
    fi
done
