#!/usr/bin/env bash
# git_remotev 1.3.2
# List remote sources of all git repos

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

# ==== main
for r in $(ls -1); do
    if [[ -d "$r/.git" ]]; then
        (
            cd "$r"
            remote=$(git remote get-url origin 2>/dev/null || echo "<no origin>")
            printf "==> ${Yel}%-35s${Rst} %s\n" "$r" "$remote"
        )
    fi
done
