#!/usr/bin/env bash
# mac_screencap 1.2.0
# Adjusts macOS SHIFT-CMD-4 screen capture settings

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVerFile=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null)
    if [[ "$LatestVerFile" =~ ^\#\! ]]; then
        LatestVer=$(echo "$LatestVerFile" | sed -n '2p' | awk '{print $NF}')
        if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
            printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
            printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
        fi
    fi
}
check_version

defaults write com.apple.screencapture location ~/Downloads
defaults write com.apple.screencapture type jpg
defaults write com.apple.screencapture name "screenshot"
defaults write com.apple.screencapture include-date -bool false
defaults write com.apple.screencapture disable-shadow -bool false
killall SystemUIServer
