#!/usr/bin/env bash
# pman 1.3.0
# Azure REST API caller

set -euo pipefail  # Fail on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
    fi
}

check_version

PrgName="pman"
PrgVer="1.1.1"

check_binary() {
    if [[ -z "$(which $1 2>/dev/null)" ]]; then
        printf "\"Missing '$1' binary!\"\n" && exit 1 
    fi
}
for B in azm curl ; do check_binary $B ; done

print_usage() {
    printf "$PrgName Azure REST API Caller v$PrgVer\n"
    printf "  Usage Examples:\n"
    printf "    $PrgName GET \"https://graph.microsoft.com/v1.0/me\"\n"
    printf "    $PrgName GET \"https://management.azure.com/subscriptions?api-version=2022-12-01\" [other curl options]\n"
    printf "    $PrgName GET \"https://graph.microsoft.com/v1.0/applications/3eec32f4-6ca1-4d1d-9335-19518aa196c4\" [other curl options]\n"
    exit 1
}

[[ $# -eq 0 || $# -lt 2 ]] && print_usage && exit 1

METHOD=$(echo "$1" | tr '[:lower:]' '[:upper:]')
URL="$2"
OPTIONAL_ARGS="${@:3}"

if [[ $URL == *"https://graph.microsoft.com"* ]]; then
    TK=$(azm -tmg)
elif [[ $URL == *"https://management.azure.com"* ]]; then
    TK=$(azm -taz)
else
    print_usage && exit 1
fi

[[ "${TK:0:3}" != "eyJ" ]] && printf "\nWARNING: Token string is invalid!\n\n"

curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $TK" -X $METHOD "$URL" $OPTIONAL_ARGS
exit 0

