#!/usr/bin/env bash
# reindex 1.3.0
# Generates this table of scripts here

set -euo pipefail  # Fail on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
    fi
}

check_version
# Define the output file
output_file="index.md"

# Start the Markdown table header
echo "# Scripts" > "$output_file"
printf "Useful shell scripts.\n\nThese can easily be called and run locally, by simply copying the \`runner\` script below, renaming it to the script you want to call from below list. For instance, to run \`build_go\`, download \`runner\` and rename it to \`build_go\`. Then when you run \`build_go\` locally it will download and run the version hosted here.\n\nThe advantage of this methodology is that you are always running _the latest version of the script_.\n\nClick on the respective link below to download and view the target script, or view source directly at <https://github.com/git719/tips/tree/main/scripts>.\n\n" >> "$output_file"

echo "| Script Name | Version    | Comment               |" >> "$output_file"
echo "|-------------|------------|-----------------------|" >> "$output_file"

# Loop through all scripts in the directory
for script in *.sh *.bash *; do
    if [[ -f $script && $(head -n 1 "$script") == "#!/usr/bin/env bash" ]]; then
        if [[ $(head -n 3 "$script" | wc -l) -ge 3 ]]; then
            # Extract details from the first 3 lines of the script
            script_name=$(basename "$script")
            version=$(sed -n '2p' "$script" | awk '{print $NF}')
            comment=$(sed -n '3p' "$script" | sed 's/# //')
            
            # Make script name a Markdown link for raw text viewing
            script_link="[$script_name]($script)"
            
            # Append to the Markdown table
            printf "| %-11s | %-10s | %-21s |\n" "$script_link" "$version" "$comment" >> "$output_file"
        fi
    fi
done

# Confirm completion
echo "Generated $output_file with script details."
