#!/usr/bin/env bash
# reindex 1.3.0
# Generates this table of scripts here

set -euo pipefail  # Fail on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

check_version() {
    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
    fi
}

check_version
# Define the output file
output_file="index.md"

# Start the Markdown table header
echo "## Scripts" > "$output_file"
printf "Useful shell scripts.\n\nTo use a script, download it locally by clicking on its respective link below. You can then run the script from its download location or move it to a directory in your system's PATH for easier access. All scripts include a \`check_version()\` function, which checks if you're running the latest version available on this site. You can also view the source code of these scripts directly on [Github](https://github.com/git719/tips/tree/main/scripts).\n\n" >> "$output_file"

echo "| Script Name | Version    | Comment               |" >> "$output_file"
echo "|-------------|------------|-----------------------|" >> "$output_file"

# Loop through all scripts in the directory
for script in *.sh *.bash *; do
    if [[ -f $script && $(head -n 1 "$script") == "#!/usr/bin/env bash" ]]; then
        if [[ $(head -n 3 "$script" | wc -l) -ge 3 ]]; then
            # Extract details from the first 3 lines of the script
            script_name=$(basename "$script")
            version=$(sed -n '2p' "$script" | awk '{print $NF}')
            comment=$(sed -n '3p' "$script" | sed 's/# //')
            
            # Make script name a Markdown link for raw text viewing
            script_link="[$script_name]($script)"
            
            # Append to the Markdown table
            printf "| %-11s | %-10s | %-21s |\n" "$script_link" "$version" "$comment" >> "$output_file"
        fi
    fi
done

printf "\n( REMINDER: Don't edit this \`index.md\` file directly -- run the \`reindex\` script instead. )\n\n" >> "$output_file"

# Confirm completion
echo "Generated $output_file with script details."
