#!/bin/bash
# RUNNER 1.0.0
# This is the generic remote script runner. Copy this file and name it exactly
# the same as published in below repo/folder that you want it to call.

set -euo pipefail
Gre='\e[1;32m' Red='\e[1;31m' Pur='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
Utility="$(basename $0)" # This script filename
#BaseUrl="https://que.one/scripts"
BaseUrl="https://raw.githubusercontent.com/git719/tips/refs/heads/main/scripts"
Remote="${BaseUrl}/${Utility}"

if [[ $# -eq 0 ]]; then
    printf "Usage: %b%s%b FILENAME\n" "${Yel}" "${Utility}" "${Rst}"
    exit 1
fi

curl -s "$Remote" | bash -s -- "$Utility" "$@"
