#!/usr/bin/env bash
# bak 1.2.1
# Backs up given file or directory

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

if [[ ! -d "$1" && ! -f "$1" ]]; then
    printf "Usage: `basename $0` <File|Directory>\n"
    exit 1
fi

nextLetter() {
    local Rest Letters=abcdefghijklmnopqrstuvwxyz
    Rest=${Letters#*$1}
    echo ${Rest:0:1}
}

DateStr="$(date +%Y%m%d)"
Target="${1}.${DateStr}a"

while [[ -d "$Target" || -e "$Target" ]]; do
    Letter=${Target:(-1)}
    if [[ "$Letter" == "z" ]]; then
        printf "Too many backups (z).\n"
        exit 1
    fi
    Target="${1}.${DateStr}$(nextLetter $Letter)"
done

cp -a "$1" "$Target"
exit 0

