#!/usr/bin/env bash
# reindex 1.5.1
# Generates table of scripts

# Define the output file
output_file="index.md"

# Start the Markdown table header
echo "## Scripts" > "$output_file"
printf "Useful shell scripts.\n\nTo use a script, download it locally by clicking on its respective link below. You can then run the script from its download location or move it to a directory in your system's PATH for easier access. To view the source code of these scripts directly go to [Github](https://github.com/git719/tips/tree/main/scripts).\n\n" >> "$output_file"

echo "| Script Name | Version    | Comment               |" >> "$output_file"
echo "|-------------|------------|-----------------------|" >> "$output_file"

# Loop through all scripts in the directory
for script in * ; do
    if [[ -f $script && $(head -n 1 "$script") == "#!/"* ]]; then
        if [[ $(head -n 3 "$script" | wc -l) -ge 3 ]]; then
            # Extract details from the first 3 lines of the script
            script_name=$(basename "$script")
            version=$(sed -n '2p' "$script" | awk '{print $NF}')
            comment=$(sed -n '3p' "$script" | sed 's/# //')
            
            # Make script name a Markdown link for raw text viewing
            script_link="[$script_name]($script)"
            
            # Append to the Markdown table
            printf "| %-11s | %-10s | %-21s |\n" "$script_link" "$version" "$comment" >> "$output_file"
        fi
    fi
done

printf "\n( REMINDER: Don't edit this \`index.md\` file directly -- run the \`reindex\` script instead. )\n\n" >> "$output_file"

# Confirm completion
echo "Generated $output_file with script details."
