#!/usr/bin/env bash
# rnlower 1.3.1
# Lowercases each file in current working directory

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

MSG="Rename ALL filenames in CWD to lowercase? Y/N "
read -p "$MSG" -n 1 && [[ ! $REPLY =~ ^[Yy]$ ]] && printf "\nAborted.\n" && exit 1
printf "\n\n"

OS=`uname | tr [A-Z] [a-z]`

for OLDNAME in * ; do
   NEWNAME=`echo "$OLDNAME/" | tr '[:upper:]' '[:lower:]'`
   # Note: The slash prevent trailing newlines from being removed by command substitution
   NEWNAME=${NEWNAME%/}          # Now remove trailing slash
   [[ "$OS" = "linux" ]]  && mv -nuv "$OLDNAME" "$NEWNAME"
   [[ "$OS" = "darwin" ]] && mv "$OLDNAME" "$NEWNAME" && echo "'$OLDNAME' -> '$NEWNAME'"
done

printf "\n"
exit 0
